name: Deploy to Vercel (push personal repository)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    permissions:
      contents: write
      actions: read

    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Setup directory structure and copy files
        run: |
          mkdir -p output/${{ github.event.repository.name }}
          cp -R * output/${{ github.event.repository.name }}/ 2>/dev/null || true
          rm -rf output/${{ github.event.repository.name }}/output || true

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "output"
          destination-github-username: DOS0313
          destination-repository-name: codezero-deploy
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
          create-target-branch-if-needed: true
